title: DCS
url: ar2em1s.github.io
baseurl: /dcs
github_username: ar2em1s

plugins:
  - jekyll-sitemap

exclude:
  - .github
  - assets/css
  - assets/js
  - build
  - .gitignore
  - .gitmodules
  - .rubocop.yml
  - .tool-versions
  - LICENCE.txt
  - package.json
  - README.md
  - tailwind.config.js
  - yarn.lock
  - lefthook.yml
  - workbox-config.js
